# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech@NYU Office Hours
email: hello@techatnyu.org
description: > # this means to ignore newlines until "baseurl:"
  We are NYC’s largest student-run organization of hackers, designers & builders. 
  We host events that unite students and help them make stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: techatnyu
github_username:  techatnyu

# Build settings
markdown: kramdown
